# This file describes the menu layout
---
- Communicate:
  title: Communicate
  links:
      - News:
        title: News
        link: News
      - Events:
        title: Events
        link: Events
      - Support:
        title: Support
        link: Support
      - Biostar:
        title: Biostar
        link: https://biostar.usegalaxy.org
- Using Galaxy:
  title: Using Galaxy
  link: UsingGalaxy
  links:
      - Servers:
        title: Servers
        link: PublicGalaxyServers
      - Learn:
        title: Learn
        link: Learn
      - Main:
        title: Main
        link: Main
      - Choices:
        title: Choices
        link: BigPicture/Choices
      - Tutorials:
        title: Support
        link: Support
- Galaxy Project:
  title: Galaxy Project
  links:
      - About:
        title: About
        link: GalaxyProject
- Deploy:
  title: Deploy Galaxy
  links:
      - Administration:
        title: Admin
        link: Admin
- Contribute:
  title: Contribute
  links:
      - Contribute:
        title: Contribute
        link: Contribute
