# This file describes the menu layout
---
- Communicate:
  title: Communicate
  links:
      - News:
        title: News
        link: news
      - Events:
        title: Events
        link: events
      - Support:
        title: Support
        link: support
      - Biostar:
        title: Biostar
        link: https://biostar.usegalaxy.org
- Using Galaxy:
  title: Using Galaxy
  link: UsingGalaxy
  links:
      - Servers:
        title: Servers
        link: PublicGalaxyServers
      - Learn:
        title: Learn
        link: Learn
      - Main:
        title: Main
        link: Main
      - Choices:
        title: Choices
        link: BigPicture/Choices
      - Tutorials:
        title: Support
        link: support
- Galaxy Project:
  title: Galaxy Project
  links:
      - About:
        title: About
        link: GalaxyProject
- Deploy:
  title: Deploy Galaxy
  links:
      - Get Galaxy:
        title: Get Galaxy
        link: Admin/GetGalaxy
      - Cloud:
        title: Cloud
        link: Cloud
      - Administration:
        title: Admin
        link: Admin
      - Tool Config:
        title: Tool Config
        link: Admin/Tools/ToolConfigSyntax
      - Tool Shed:
        title: Tool Shed
        link: ToolShed
- Contribute:
  title: Contribute
  links:
      - Develop:
        title: Develop
        link: Develop
      - Tools:
        title: Tools
        link: Tools
      - Issues & Requests:
        title: Issues & Requests
        link: Issues
      - Logs:
        title: Logs
        link: Community/Logs
      - Deployments:
        title: Deployments
        link: Community/Deployments
      - Teach:
        title: Teach
        link: Teach
